import { Agent, TaskContract, SwarmEventLog, Deliverable } from '@/types';

export const SEED_AGENTS: Agent[] = [
  {
    id: 'agent_nova',
    name: 'Agent Nova',
    role: 'worker',
    specialty: 'Data Harvester',
    avatar: '🛰️',
    colorScheme: {
      primary: '#8055F7',
      secondary: '#F3E8FF',
      accent: '#C084FC',
      border: '#E9D5FF',
    },
    payoutEmail: 'nova.data@payagent.sandbox',
    ratePerTask: 3.50,
    rating: 4.8,
    tasks: 12,
    completedTasks: 10,
    inProgressTasks: 2,
    status: 'working',
    currentTaskId: 'DATA-088',
  },
  {
    id: 'agent_cipher',
    name: 'Agent Cipher',
    role: 'worker',
    specialty: 'Security Auditor',
    avatar: '🛡️',
    colorScheme: {
      primary: '#1E40AF',
      secondary: '#DBEAFE',
      accent: '#3B82F6',
      border: '#BFDBFE',
    },
    payoutEmail: 'cipher.sec@payagent.sandbox',
    ratePerTask: 6.00,
    rating: 4.9,
    tasks: 11,
    completedTasks: 9,
    inProgressTasks: 2,
    status: 'settled',
    currentTaskId: 'SEC-014',
  },
  {
    id: 'agent_synthex',
    name: 'Agent Synthex',
    role: 'worker',
    specialty: 'Technical Writer',
    avatar: '⚡',
    colorScheme: {
      primary: '#DB2777',
      secondary: '#FCE7F3',
      accent: '#F472B6',
      border: '#FBCFE8',
    },
    payoutEmail: 'synthex.write@payagent.sandbox',
    ratePerTask: 4.50,
    rating: 4.7,
    tasks: 10,
    completedTasks: 8,
    inProgressTasks: 2,
    status: 'working',
    currentTaskId: 'DOC-103',
  },
  {
    id: 'agent_metric',
    name: 'Agent Metric',
    role: 'worker',
    specialty: 'Market Quant',
    avatar: '📈',
    colorScheme: {
      primary: '#059669',
      secondary: '#D1FAE5',
      accent: '#34D399',
      border: '#A7F3D0',
    },
    payoutEmail: 'metric.quant@payagent.sandbox',
    ratePerTask: 4.00,
    rating: 4.6,
    tasks: 8,
    completedTasks: 6,
    inProgressTasks: 2,
    status: 'under_qa',
    currentTaskId: 'MKT-027',
  },
];

export const SEED_CONTRACTS: TaskContract[] = [
  {
    id: 'SEC-014',
    missionId: 'MSN-INIT-01',
    title: 'Audit PayPal API for CVEs',
    description: 'Perform static vulnerability scan, inspect token expiry rotation, and test OWASP API Top 10 vulnerabilities.',
    assignedAgentId: 'agent_cipher',
    assignedAgentName: 'Cipher',
    assignedAgentEmail: 'cipher.sec@payagent.sandbox',
    budget: 15.00,
    status: 'settled',
    acceptanceCriteria: [
      'OWASP API Top 10 Compliance Review',
      'Verify HMAC-SHA256 signature verification code',
      'Produce CVE classifications with CVSS v3.1 scoring',
    ],
    paypalOrderId: 'ORD-7HJ8K2',
    paypalAuthorizationId: 'AUTH-9X2L8M',
    paypalPayoutBatchId: 'PO-BATCH-9A2F3B',
    paypalPayoutItemId: 'ITEM-8812',
    paypalPayoutStatus: 'SUCCESS',
    createdAt: '2026-10-04T13:40:00Z',
    completedAt: '2026-10-04T14:06:00Z',
    paidAt: '2026-10-04T14:06:24Z',
    deliverable: {
      summary: 'Completed comprehensive vulnerability analysis on payment endpoint routers.',
      content: `# Payment Gateway Security Audit\n## Executive Summary\nWe analyzed the API surface and identified 3 high severity vulnerabilities.\n\n### Findings:\n1. **OWASP API3:2023 Broken Object Property Level Authorization**: Secondary query projections lacked tenant boundary checks.\n2. **Replay Protection**: Added nonces check for PayPal webhook headers.\n3. **Rate Limiting**: Applied token bucket algorithm.\n\n\`\`\`typescript\n// Remediation diff applied:\nexport function verifyWebhook(req: Request) {\n  const signature = req.headers.get('PAYPAL-AUTH-ALGO');\n  if (!signature) throw new Error('Invalid signature');\n  return true;\n}\n\`\`\`\n\n*Artifact Hash: sha256:e8b23c91a0f88219*`,
      executionTimeMs: 1450,
      qualityScore: 92,
      evaluatorFeedback: 'JudgeLex QA: Exceeds acceptance threshold (92/100). All OWASP tests passed. Code diff clean and reproducible.',
      verifiedAt: '2026-10-04T14:06:23Z',
      criteriaResults: [
        { name: 'OWASP Compliance', passed: true, evidence: 'All 10 endpoints verified against OWASP API rules.' },
        { name: 'Schema Validity', passed: true, evidence: 'Strict JSON schema adheres to RFC 8259.' },
        { name: 'Code Diff Check', passed: true, evidence: 'Git patch compiles without warnings.' },
        { name: 'Report Quality', passed: true, evidence: 'CVSS scores provided for all 3 vectors.' },
      ],
    },
  },
  {
    id: 'MKT-027',
    missionId: 'MSN-INIT-01',
    title: 'Competitor Pricing Analysis',
    description: 'Scrape cross-platform SaaS tier pricing and evaluate margin opportunities.',
    assignedAgentId: 'agent_metric',
    assignedAgentName: 'Metric',
    assignedAgentEmail: 'metric.quant@payagent.sandbox',
    budget: 20.00,
    status: 'under_qa',
    acceptanceCriteria: [
      'Extract pricing across 6 enterprise payment providers',
      'Calculate interchange & processing markup deltas',
      'Provide price-elasticity churn estimates',
    ],
    paypalOrderId: 'ORD-8KL99P',
    paypalAuthorizationId: 'AUTH-4P7N1Q',
    createdAt: '2026-10-04T13:45:00Z',
    deliverable: {
      summary: 'Compiled pricing matrices from Stripe, Adyen, Square, and Braintree.',
      content: `# Competitor Pricing & Interchange Arbitrage\n## Key Metrics\n- Average Domestic Transaction Fee: 2.9% + $0.30\n- Cross-border Surcharge: 1.5%\n- Recommendation: Introduce tiered volume discounts at >$50k monthly volume.`,
      executionTimeMs: 1980,
      qualityScore: 78,
      evaluatorFeedback: 'JudgeLex QA: In review. Score 78/100 (Below 80 threshold). Missing 2 competitor breakdown matrices.',
      criteriaResults: [
        { name: 'OWASP Compliance', passed: true, evidence: 'N/A for quantitative data.' },
        { name: 'Schema Validity', passed: true, evidence: 'Dataset validated.' },
        { name: 'Code Diff Check', passed: false, evidence: 'Data incomplete for 2 vendors.' },
        { name: 'Report Quality', passed: true, evidence: 'Clear summary and charts.' },
      ],
    },
  },
  {
    id: 'DOC-103',
    missionId: 'MSN-INIT-01',
    title: 'Remediation Playbook',
    description: 'Synthesize findings into an executive-ready security implementation guide.',
    assignedAgentId: 'agent_synthex',
    assignedAgentName: 'Synthex',
    assignedAgentEmail: 'synthex.write@payagent.sandbox',
    budget: 12.50,
    status: 'in_progress',
    acceptanceCriteria: [
      'Write step-by-step remediation guide',
      'Include roll-back contingency plan',
      'Provide compliance audit checklist',
    ],
    paypalOrderId: 'ORD-7HJ8K2',
    paypalAuthorizationId: 'AUTH-7HJ8K2',
    createdAt: '2026-10-04T13:50:00Z',
  },
  {
    id: 'DATA-088',
    missionId: 'MSN-INIT-01',
    title: 'API Schema Mapping',
    description: 'Map REST and GraphQL surface endpoints and normalize data types.',
    assignedAgentId: 'agent_nova',
    assignedAgentName: 'Nova',
    assignedAgentEmail: 'nova.data@payagent.sandbox',
    budget: 10.00,
    status: 'escrow_authorized',
    acceptanceCriteria: [
      'Extract OpenAPI 3.1 specification',
      'Flag deprecated endpoints and auth headers',
      'Generate mock JSON fixtures for testing',
    ],
    paypalOrderId: 'ORD-3K9MZ1',
    paypalAuthorizationId: 'AUTH-3K9MZ1',
    createdAt: '2026-10-04T13:55:00Z',
  },
  {
    id: 'RISK-021',
    missionId: 'MSN-INIT-01',
    title: 'Payment Flow Threat Model',
    description: 'Identify multi-party fraud vectors in merchant split settlements.',
    assignedAgentId: 'agent_cipher',
    assignedAgentName: 'Cipher',
    assignedAgentEmail: 'cipher.sec@payagent.sandbox',
    budget: 18.00,
    status: 'disputed',
    acceptanceCriteria: [
      'STRIDE threat modeling on webhook lifecycle',
      'Simulate MITM replay attacks on PayPal notifications',
      'Define automated dispute evidence requirements',
    ],
    paypalOrderId: 'ORD-4L2K9D',
    paypalAuthorizationId: 'AUTH-4L2K9D',
    paypalPayoutBatchId: 'PO-BATCH-4L2K9D',
    createdAt: '2026-10-04T13:30:00Z',
    deliverable: {
      summary: 'Drafted threat model document. Escrow paused due to low coverage score.',
      content: `# Threat Model: Multi-Party Settlement\n\nIdentified potential vulnerability in callback webhook verification. Remediation required.`,
      executionTimeMs: 1200,
      qualityScore: 65,
      evaluatorFeedback: 'JudgeLex QA: Disputed (Score 65/100). Threat model lacks STRIDE matrix for merchant dispute scenarios.',
    },
  },
];

export const SEED_EVENTS: SwarmEventLog[] = [
  {
    id: 'EVT-1',
    timestamp: '14:05:12',
    source: 'ORCHESTRATOR',
    category: 'planning',
    message: 'Goal ingested and decomposed into 4 contracts',
  },
  {
    id: 'EVT-2',
    timestamp: '14:05:14',
    source: 'PAYPAL_ESCROW',
    category: 'escrow',
    message: 'Order authorized $15.00 ORD-7HJ8K2',
  },
  {
    id: 'EVT-3',
    timestamp: '14:05:16',
    source: 'AGENT_NODE',
    category: 'bidding',
    message: 'Agent Cipher claimed SEC-014',
  },
  {
    id: 'EVT-4',
    timestamp: '14:06:23',
    source: 'JUDGELEX_QA',
    category: 'qa',
    message: 'Deliverable scored 92/100 • Approved',
  },
  {
    id: 'EVT-5',
    timestamp: '14:06:24',
    source: 'PAYPAL_PAYOUT',
    category: 'payout',
    message: 'Payout sent to cipher.sec@payagent.sandbox PO-BATCH-9A2F3B',
  },
  {
    id: 'EVT-6',
    timestamp: '14:07:01',
    source: 'GUARDRAIL',
    category: 'safety',
    message: 'Budget check passed (≤ $15.00)',
  },
  {
    id: 'EVT-7',
    timestamp: '14:08:12',
    source: 'AGENT_NODE',
    category: 'execution',
    message: 'Agent Nova started data collection...',
  },
  {
    id: 'EVT-8',
    timestamp: '14:08:45',
    source: 'SYSTEM',
    category: 'system',
    message: '3 contracts in progress, 1 under QA',
  },
];

export function planMissionTasks(missionId: string, goal: string): TaskContract[] {
  return [
    {
      id: `TSK-${Math.random().toString(36).substring(2, 7).toUpperCase()}`,
      missionId,
      title: 'Endpoint Vulnerability & Surface Discovery',
      description: 'Map REST attack surfaces and analyze rate-limiting thresholds.',
      assignedAgentId: 'agent_nova',
      assignedAgentName: 'Nova',
      assignedAgentEmail: 'nova.data@payagent.sandbox',
      budget: 3.50,
      status: 'pending',
      acceptanceCriteria: ['Identify top 5 API vulnerabilities', 'Extract schema entropy'],
      createdAt: new Date().toISOString(),
    },
    {
      id: `TSK-${Math.random().toString(36).substring(2, 7).toUpperCase()}`,
      missionId,
      title: 'Cryptographic Auth & Token Expiry Audit',
      description: 'Audit OAuth2 token exchange and replay protection.',
      assignedAgentId: 'agent_cipher',
      assignedAgentName: 'Cipher',
      assignedAgentEmail: 'cipher.sec@payagent.sandbox',
      budget: 6.00,
      status: 'pending',
      acceptanceCriteria: ['Verify HMAC-SHA256 signature verification code', 'Audit token TTL'],
      createdAt: new Date().toISOString(),
    },
    {
      id: `TSK-${Math.random().toString(36).substring(2, 7).toUpperCase()}`,
      missionId,
      title: 'Executive Remediation Playbook',
      description: 'Synthesize findings into executive risk scores and PR diffs.',
      assignedAgentId: 'agent_synthex',
      assignedAgentName: 'Synthex',
      assignedAgentEmail: 'synthex.write@payagent.sandbox',
      budget: 4.50,
      status: 'pending',
      acceptanceCriteria: ['Complete executive summary', 'Actionable code patches'],
      createdAt: new Date().toISOString(),
    },
  ];
}

export function generateSyntheticDeliverable(task: TaskContract): Deliverable {
  return {
    summary: `Completed thorough inspection for "${task.title}". Identified core vectors and supplied verified patch diffs.`,
    content: `# Audit Report: ${task.title}\n\n**Status**: PASSED ACCEPTANCE CRITERIA\n\n### Key Findings:\n1. OWASP API3 Broken Object Property Authorization resolved.\n2. Replay protection verified on PayPal webhook headers.\n3. Rate limiting threshold calibrated.\n\n*Artifact Hash: sha256:${Math.random().toString(36).substring(2, 12)}*`,
    executionTimeMs: 1420,
    qualityScore: 92,
    evaluatorFeedback: 'JudgeLex QA: Criteria met with full verification. Release of PayPal Escrow approved.',
    verifiedAt: new Date().toISOString(),
    criteriaResults: [
      { name: 'OWASP Compliance', passed: true, evidence: 'Verified against OWASP API rules.' },
      { name: 'Schema Validity', passed: true, evidence: 'Strict JSON schema verified.' },
      { name: 'Code Diff Check', passed: true, evidence: 'Git patch clean.' },
      { name: 'Report Quality', passed: true, evidence: 'Full CVSS scores supplied.' },
    ],
  };
}

export const PRESET_MISSIONS = [
  {
    title: 'Autonomous Security & Risk Audit for Payment Gateway API',
    goal: 'Audit the payment gateway API, identify security weaknesses, and produce a CVE remediation playbook.',
    budget: 18.00,
  },
  {
    title: 'Competitor Pricing Arbitrage & Market Intelligence Dossier',
    goal: 'Scrape cross-platform SaaS tier pricing, compute elasticity indices, and generate an executive go-to-market pricing proposal.',
    budget: 15.00,
  },
  {
    title: 'AI Agent-to-Agent Micro-Payment Commerce Whitepaper',
    goal: 'Research cryptographic escrow patterns, benchmark PayPal Payouts settlement latency, and synthesize a multi-agent economic specification.',
    budget: 16.50,
  },
];


